// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillBridge.Infrastructure.Data;

#nullable disable

namespace SkillBridge.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310180654_AddContactAndSeedData")]
    partial class AddContactAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkillBridge.Core.Entities.OtpVerification", b =>
                {
                    b.Property<int>("OtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OtpId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OtpId");

                    b.ToTable("OtpVerifications");
                });

            modelBuilder.Entity("SkillBridge.Core.Entities.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An intelligent tutoring system that personalizes learning paths using NLP. Helps students understand complex topics through adaptive quizzing and content recommendations.",
                            OwnerId = 2,
                            Status = "Open",
                            Title = "AI Study Assistant"
                        },
                        new
                        {
                            ProjectId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Deploy IoT sensors across campus to monitor environmental data (temperature, air quality, occupancy) and visualize it on a real-time dashboard.",
                            OwnerId = 7,
                            Status = "Open",
                            Title = "Smart Campus IoT Network"
                        },
                        new
                        {
                            ProjectId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A web platform that matches final-year students with internships and part-time jobs based on their skills and project experience. Built with Angular + ASP.NET Core.",
                            OwnerId = 1,
                            Status = "Open",
                            Title = "SkillMatch Job Portal"
                        },
                        new
                        {
                            ProjectId = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "End-to-end encrypted peer-to-peer file sharing platform. Implements AES-256 encryption, digital signatures, and zero-knowledge proofs for privacy.",
                            OwnerId = 9,
                            Status = "Open",
                            Title = "Secure File Sharing App"
                        },
                        new
                        {
                            ProjectId = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mobile app built with Flutter to track fitness goals, nutrition, and health metrics. Integrates with wearables and provides AI-powered insights.",
                            OwnerId = 8,
                            Status = "Open",
                            Title = "Cross-Platform Health Tracker"
                        },
                        new
                        {
                            ProjectId = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A microservices tool that analyzes cloud resource usage on AWS/Azure and recommends cost-saving strategies. Uses Kubernetes and automated scaling policies.",
                            OwnerId = 15,
                            Status = "Open",
                            Title = "Cloud Cost Optimizer"
                        },
                        new
                        {
                            ProjectId = 7,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Machine learning pipeline that ingests live stock market data, applies LSTM neural networks, and generates buy/sell signals with confidence scores.",
                            OwnerId = 11,
                            Status = "Open",
                            Title = "Real-time Stock Predictor"
                        },
                        new
                        {
                            ProjectId = 8,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hardware implementation of a digital signal processor on FPGA for real-time audio filtering and FFT analysis. Targets Xilinx Artix-7 development board.",
                            OwnerId = 3,
                            Status = "Open",
                            Title = "FPGA-Based Signal Processor"
                        });
                });

            modelBuilder.Entity("SkillBridge.Core.Entities.ProjectSkill", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("ProjectId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("ProjectSkills");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            SkillId = 10
                        },
                        new
                        {
                            ProjectId = 1,
                            SkillId = 6
                        },
                        new
                        {
                            ProjectId = 1,
                            SkillId = 13
                        },
                        new
                        {
                            ProjectId = 1,
                            SkillId = 1
                        },
                        new
                        {
                            ProjectId = 2,
                            SkillId = 16
                        },
                        new
                        {
                            ProjectId = 2,
                            SkillId = 10
                        },
                        new
                        {
                            ProjectId = 2,
                            SkillId = 11
                        },
                        new
                        {
                            ProjectId = 2,
                            SkillId = 12
                        },
                        new
                        {
                            ProjectId = 3,
                            SkillId = 1
                        },
                        new
                        {
                            ProjectId = 3,
                            SkillId = 9
                        },
                        new
                        {
                            ProjectId = 3,
                            SkillId = 3
                        },
                        new
                        {
                            ProjectId = 3,
                            SkillId = 4
                        },
                        new
                        {
                            ProjectId = 4,
                            SkillId = 20
                        },
                        new
                        {
                            ProjectId = 4,
                            SkillId = 10
                        },
                        new
                        {
                            ProjectId = 4,
                            SkillId = 5
                        },
                        new
                        {
                            ProjectId = 5,
                            SkillId = 14
                        },
                        new
                        {
                            ProjectId = 5,
                            SkillId = 15
                        },
                        new
                        {
                            ProjectId = 5,
                            SkillId = 12
                        },
                        new
                        {
                            ProjectId = 5,
                            SkillId = 2
                        },
                        new
                        {
                            ProjectId = 6,
                            SkillId = 5
                        },
                        new
                        {
                            ProjectId = 6,
                            SkillId = 17
                        },
                        new
                        {
                            ProjectId = 6,
                            SkillId = 3
                        },
                        new
                        {
                            ProjectId = 6,
                            SkillId = 4
                        },
                        new
                        {
                            ProjectId = 7,
                            SkillId = 10
                        },
                        new
                        {
                            ProjectId = 7,
                            SkillId = 6
                        },
                        new
                        {
                            ProjectId = 7,
                            SkillId = 13
                        },
                        new
                        {
                            ProjectId = 7,
                            SkillId = 18
                        },
                        new
                        {
                            ProjectId = 8,
                            SkillId = 8
                        },
                        new
                        {
                            ProjectId = 8,
                            SkillId = 7
                        },
                        new
                        {
                            ProjectId = 8,
                            SkillId = 16
                        },
                        new
                        {
                            ProjectId = 8,
                            SkillId = 10
                        });
                });

            modelBuilder.Entity("SkillBridge.Core.Entities.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkillId");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            SkillId = 1,
                            Category = "Frontend",
                            Name = "Angular"
                        },
                        new
                        {
                            SkillId = 2,
                            Category = "Frontend",
                            Name = "React"
                        },
                        new
                        {
                            SkillId = 3,
                            Category = "Backend",
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            SkillId = 4,
                            Category = "Database",
                            Name = "SQL Server"
                        },
                        new
                        {
                            SkillId = 5,
                            Category = "DevOps",
                            Name = "Docker"
                        },
                        new
                        {
                            SkillId = 6,
                            Category = "AI/ML",
                            Name = "Machine Learning"
                        },
                        new
                        {
                            SkillId = 7,
                            Category = "Hardware",
                            Name = "Circuit Design"
                        },
                        new
                        {
                            SkillId = 8,
                            Category = "Hardware",
                            Name = "FPGA"
                        },
                        new
                        {
                            SkillId = 9,
                            Category = "Frontend",
                            Name = "TypeScript"
                        },
                        new
                        {
                            SkillId = 10,
                            Category = "Backend",
                            Name = "Python"
                        },
                        new
                        {
                            SkillId = 11,
                            Category = "Backend",
                            Name = "Node.js"
                        },
                        new
                        {
                            SkillId = 12,
                            Category = "Database",
                            Name = "MongoDB"
                        },
                        new
                        {
                            SkillId = 13,
                            Category = "AI/ML",
                            Name = "TensorFlow"
                        },
                        new
                        {
                            SkillId = 14,
                            Category = "Mobile",
                            Name = "Flutter"
                        },
                        new
                        {
                            SkillId = 15,
                            Category = "Mobile",
                            Name = "Kotlin"
                        },
                        new
                        {
                            SkillId = 16,
                            Category = "Hardware",
                            Name = "Arduino"
                        },
                        new
                        {
                            SkillId = 17,
                            Category = "DevOps",
                            Name = "Kubernetes"
                        },
                        new
                        {
                            SkillId = 18,
                            Category = "AI/ML",
                            Name = "Data Science"
                        },
                        new
                        {
                            SkillId = 19,
                            Category = "Frontend",
                            Name = "Vue.js"
                        },
                        new
                        {
                            SkillId = 20,
                            Category = "Security",
                            Name = "Cyber Security"
                        });
                });

            modelBuilder.Entity("SkillBridge.Core.Entities.TeamRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("TeamRequests");
                });

            modelBuilder.Entity("SkillBridge.Core.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Bio = "Passionate about full-stack web development and open-source. Building scalable apps with Angular and .NET.",
                            Contact = "+91 98765 43210",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "BTech - CSE - Computer Science and Engineering",
                            Email = "arjun.sharma@student.edu",
                            FullName = "Arjun Sharma",
                            IsVerified = true,
                            PasswordHash = "$2a$11$K7rRnPQx.Wlz9N8Tz1eM4.kVeHNzFpLQtmYs3R6wXdJb2oOhXDqi",
                            Year = 3
                        },
                        new
                        {
                            UserId = 2,
                            Bio = "AI/ML enthusiast focused on NLP and computer vision. Working on real-world datasets for my final year project.",
                            Contact = "+91 87654 32109",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "BTech - AIML - Artificial Intelligence and Machine Learning",
                            Email = "priya.patel@student.edu",
                            FullName = "Priya Patel",
                            IsVerified = true,
                            PasswordHash = "$2a$11$K7rRnPQx.Wlz9N8Tz1eM4.kVeHNzFpLQtmYs3R6wXdJb2oOhXDqi",
                            Year = 3
                        },
                        new
                        {
                            UserId = 3,
                            Bio = "Hardware and embedded systems aficionado. Love building IoT sensors and FPGA-based projects.",
                            Contact = "+91 76543 21098",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "BTech - ECE - Electronics and Communication Engineering",
                            Email = "rahul.nair@student.edu",
                            FullName = "Rahul Nair",
                            IsVerified = true,
                            PasswordHash = "$2a$11$K7rRnPQx.Wlz9N8Tz1eM4.kVeHNzFpLQtmYs3R6wXdJb2oOhXDqi",
                            Year = 4
                        },
                        new
                        {
                            UserId = 4,
                            Bio = "Data science student specializing in statistical modeling and data visualization using Python and Tableau.",
                            Contact = "+91 65432 10987",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "BTech - DS - Data Science and Engineering",
                            Email = "sneha.reddy@student.edu",
                            FullName = "Sneha Reddy",
                            IsVerified = true,
                            PasswordHash = "$2a$11$K7rRnPQx.Wlz9N8Tz1eM4.kVeHNzFpLQtmYs3R6wXdJb2oOhXDqi",
                            Year = 2
                        },
                        new
                        {
                            UserId = 5,
                            Bio = "Backend developer and cloud native engineer. Interested in microservices, Docker, and Kubernetes deployments.",
                            Contact = "+91 54321 09876",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "BTech - CSE - Computer Science and Engineering",
                            Email = "vikram.singh@student.edu",
                            FullName = "Vikram Singh",
                            IsVerified = true,
                            PasswordHash = "$2a$11$K7rRnPQx.Wlz9N8Tz1eM4.kVeHNzFpLQtmYs3R6wXdJb2oOhXDqi",
                            Year = 4
                        },
                        new
                        {
                            UserId = 6,
                            Bio = "Post-graduate researcher in deep learning and autonomous systems. Kaggle competitions enthusiast.",
                            Contact = "+91 43210 98765",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "MTech - M.AI - Artificial Intelligence",
                            Email = "ananya.k@student.edu",
                            FullName = "Ananya Krishnan",
                            IsVerified = true,
                            PasswordHash = "$2a$11$K7rRnPQx.Wlz9N8Tz1eM4.kVeHNzFpLQtmYs3R6wXdJb2oOhXDqi",
                            Year = 1
                        },
                        new
                        {
                            UserId = 7,
                            Bio = "IoT developer connecting physical devices to cloud platforms. Experience with Arduino, Raspberry Pi, and AWS IoT.",
                            Contact = "+91 32109 87654",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "BTech - IoT - Internet of Things",
                            Email = "karthik.v@student.edu",
                            FullName = "Karthik Venkat",
                            IsVerified = true,
                            PasswordHash = "$2a$11$K7rRnPQx.Wlz9N8Tz1eM4.kVeHNzFpLQtmYs3R6wXdJb2oOhXDqi",
                            Year = 3
                        },
                        new
                        {
                            UserId = 8,
                            Bio = "Mobile app developer creating cross-platform experiences using Flutter and Firebase. Published 2 apps on Play Store.",
                            Contact = "+91 21098 76543",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "BTech - IT - Information Technology",
                            Email = "divya.menon@student.edu",
                            FullName = "Divya Menon",
                            IsVerified = true,
                            PasswordHash = "$2a$11$K7rRnPQx.Wlz9N8Tz1eM4.kVeHNzFpLQtmYs3R6wXdJb2oOhXDqi",
                            Year = 3
                        },
                        new
                        {
                            UserId = 9,
                            Bio = "Cybersecurity student focused on ethical hacking, penetration testing, and network security protocols.",
                            Contact = "+91 10987 65432",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "BTech - CYS - Cyber Security",
                            Email = "suresh.kumar@student.edu",
                            FullName = "Suresh Kumar",
                            IsVerified = true,
                            PasswordHash = "$2a$11$K7rRnPQx.Wlz9N8Tz1eM4.kVeHNzFpLQtmYs3R6wXdJb2oOhXDqi",
                            Year = 4
                        },
                        new
                        {
                            UserId = 10,
                            Bio = "Frontend developer who loves creating beautiful UIs. Skilled in React, Vue.js, and UI/UX design principles.",
                            Contact = "+91 09876 54321",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "BTech - CSE - Computer Science and Engineering",
                            Email = "lakshmi.d@student.edu",
                            FullName = "Lakshmi Devi",
                            IsVerified = true,
                            PasswordHash = "$2a$11$K7rRnPQx.Wlz9N8Tz1eM4.kVeHNzFpLQtmYs3R6wXdJb2oOhXDqi",
                            Year = 2
                        },
                        new
                        {
                            UserId = 11,
                            Bio = "Data engineer passionate about building data pipelines and ML workflows. Proficient in Python, Spark, and TensorFlow.",
                            Contact = "+91 98761 23456",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "MTech - M.DS - Data Science",
                            Email = "ravi.teja@student.edu",
                            FullName = "Ravi Teja",
                            IsVerified = true,
                            PasswordHash = "$2a$11$K7rRnPQx.Wlz9N8Tz1eM4.kVeHNzFpLQtmYs3R6wXdJb2oOhXDqi",
                            Year = 2
                        },
                        new
                        {
                            UserId = 12,
                            Bio = "Full-stack developer with expertise in MERN stack. Interested in building SaaS products and developer tools.",
                            Contact = "+91 87652 34567",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "BTech - CSE - Computer Science and Engineering",
                            Email = "pooja.iyer@student.edu",
                            FullName = "Pooja Iyer",
                            IsVerified = true,
                            PasswordHash = "$2a$11$K7rRnPQx.Wlz9N8Tz1eM4.kVeHNzFpLQtmYs3R6wXdJb2oOhXDqi",
                            Year = 3
                        },
                        new
                        {
                            UserId = 13,
                            Bio = "Computer vision researcher working on real-time object detection using YOLO and OpenCV.",
                            Contact = "+91 76543 45678",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "BTech - AIML - Artificial Intelligence and Machine Learning",
                            Email = "aditya.rao@student.edu",
                            FullName = "Aditya Rao",
                            IsVerified = true,
                            PasswordHash = "$2a$11$K7rRnPQx.Wlz9N8Tz1eM4.kVeHNzFpLQtmYs3R6wXdJb2oOhXDqi",
                            Year = 4
                        },
                        new
                        {
                            UserId = 14,
                            Bio = "First-year student excited about software development. Learning web technologies and competitive programming.",
                            Contact = "+91 65432 56789",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "BTech - CSE - Computer Science and Engineering",
                            Email = "meera.joshi@student.edu",
                            FullName = "Meera Joshi",
                            IsVerified = true,
                            PasswordHash = "$2a$11$K7rRnPQx.Wlz9N8Tz1eM4.kVeHNzFpLQtmYs3R6wXdJb2oOhXDqi",
                            Year = 1
                        },
                        new
                        {
                            UserId = 15,
                            Bio = "Cloud architect student specializing in AWS and Azure. Building serverless architectures for final year project.",
                            Contact = "+91 54321 67890",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "BTech - CC - Cloud Computing",
                            Email = "nikhil.gupta@student.edu",
                            FullName = "Nikhil Gupta",
                            IsVerified = true,
                            PasswordHash = "$2a$11$K7rRnPQx.Wlz9N8Tz1eM4.kVeHNzFpLQtmYs3R6wXdJb2oOhXDqi",
                            Year = 4
                        });
                });

            modelBuilder.Entity("SkillBridge.Core.Entities.UserSkill", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<string>("Proficiency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("UserSkills");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            SkillId = 1,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 1,
                            SkillId = 9,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 1,
                            SkillId = 3,
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            UserId = 1,
                            SkillId = 4,
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            UserId = 1,
                            SkillId = 5,
                            Proficiency = "Beginner"
                        },
                        new
                        {
                            UserId = 2,
                            SkillId = 10,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 2,
                            SkillId = 6,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 2,
                            SkillId = 13,
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            UserId = 2,
                            SkillId = 18,
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            UserId = 2,
                            SkillId = 4,
                            Proficiency = "Beginner"
                        },
                        new
                        {
                            UserId = 3,
                            SkillId = 8,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 3,
                            SkillId = 7,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 3,
                            SkillId = 16,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 3,
                            SkillId = 10,
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            UserId = 3,
                            SkillId = 4,
                            Proficiency = "Beginner"
                        },
                        new
                        {
                            UserId = 4,
                            SkillId = 10,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 4,
                            SkillId = 18,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 4,
                            SkillId = 6,
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            UserId = 4,
                            SkillId = 4,
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            UserId = 4,
                            SkillId = 13,
                            Proficiency = "Beginner"
                        },
                        new
                        {
                            UserId = 5,
                            SkillId = 5,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 5,
                            SkillId = 17,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 5,
                            SkillId = 3,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 5,
                            SkillId = 4,
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            UserId = 5,
                            SkillId = 10,
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            UserId = 6,
                            SkillId = 6,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 6,
                            SkillId = 13,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 6,
                            SkillId = 10,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 6,
                            SkillId = 18,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 6,
                            SkillId = 1,
                            Proficiency = "Beginner"
                        },
                        new
                        {
                            UserId = 7,
                            SkillId = 16,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 7,
                            SkillId = 7,
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            UserId = 7,
                            SkillId = 10,
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            UserId = 7,
                            SkillId = 11,
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            UserId = 7,
                            SkillId = 12,
                            Proficiency = "Beginner"
                        },
                        new
                        {
                            UserId = 8,
                            SkillId = 14,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 8,
                            SkillId = 15,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 8,
                            SkillId = 2,
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            UserId = 8,
                            SkillId = 12,
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            UserId = 8,
                            SkillId = 11,
                            Proficiency = "Beginner"
                        },
                        new
                        {
                            UserId = 9,
                            SkillId = 20,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 9,
                            SkillId = 10,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 9,
                            SkillId = 5,
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            UserId = 9,
                            SkillId = 4,
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            UserId = 9,
                            SkillId = 11,
                            Proficiency = "Beginner"
                        },
                        new
                        {
                            UserId = 10,
                            SkillId = 2,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 10,
                            SkillId = 19,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 10,
                            SkillId = 9,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 10,
                            SkillId = 1,
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            UserId = 10,
                            SkillId = 11,
                            Proficiency = "Beginner"
                        },
                        new
                        {
                            UserId = 11,
                            SkillId = 10,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 11,
                            SkillId = 13,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 11,
                            SkillId = 18,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 11,
                            SkillId = 6,
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            UserId = 11,
                            SkillId = 4,
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            UserId = 12,
                            SkillId = 2,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 12,
                            SkillId = 11,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 12,
                            SkillId = 12,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 12,
                            SkillId = 9,
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            UserId = 12,
                            SkillId = 5,
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            UserId = 13,
                            SkillId = 10,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 13,
                            SkillId = 6,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 13,
                            SkillId = 13,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 13,
                            SkillId = 1,
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            UserId = 13,
                            SkillId = 18,
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            UserId = 14,
                            SkillId = 1,
                            Proficiency = "Beginner"
                        },
                        new
                        {
                            UserId = 14,
                            SkillId = 9,
                            Proficiency = "Beginner"
                        },
                        new
                        {
                            UserId = 14,
                            SkillId = 2,
                            Proficiency = "Beginner"
                        },
                        new
                        {
                            UserId = 14,
                            SkillId = 4,
                            Proficiency = "Beginner"
                        },
                        new
                        {
                            UserId = 14,
                            SkillId = 10,
                            Proficiency = "Beginner"
                        },
                        new
                        {
                            UserId = 15,
                            SkillId = 5,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 15,
                            SkillId = 17,
                            Proficiency = "Expert"
                        },
                        new
                        {
                            UserId = 15,
                            SkillId = 3,
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            UserId = 15,
                            SkillId = 1,
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            UserId = 15,
                            SkillId = 4,
                            Proficiency = "Intermediate"
                        });
                });

            modelBuilder.Entity("SkillBridge.Core.Entities.Project", b =>
                {
                    b.HasOne("SkillBridge.Core.Entities.User", "Owner")
                        .WithMany("OwnedProjects")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SkillBridge.Core.Entities.ProjectSkill", b =>
                {
                    b.HasOne("SkillBridge.Core.Entities.Project", "Project")
                        .WithMany("ProjectSkills")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillBridge.Core.Entities.Skill", "Skill")
                        .WithMany("ProjectSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SkillBridge.Core.Entities.TeamRequest", b =>
                {
                    b.HasOne("SkillBridge.Core.Entities.Project", "Project")
                        .WithMany("TeamRequests")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillBridge.Core.Entities.User", "Receiver")
                        .WithMany("ReceivedRequests")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillBridge.Core.Entities.User", "Sender")
                        .WithMany("SentRequests")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("SkillBridge.Core.Entities.UserSkill", b =>
                {
                    b.HasOne("SkillBridge.Core.Entities.Skill", "Skill")
                        .WithMany("UserSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillBridge.Core.Entities.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillBridge.Core.Entities.Project", b =>
                {
                    b.Navigation("ProjectSkills");

                    b.Navigation("TeamRequests");
                });

            modelBuilder.Entity("SkillBridge.Core.Entities.Skill", b =>
                {
                    b.Navigation("ProjectSkills");

                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("SkillBridge.Core.Entities.User", b =>
                {
                    b.Navigation("OwnedProjects");

                    b.Navigation("ReceivedRequests");

                    b.Navigation("SentRequests");

                    b.Navigation("UserSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
